<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <title>Class Timetable - {{ $classroomId }} (Sem {{ $semester }})</title>
  <script src="https://cdn.jsdelivr.net/npm/@tailwindcss/browser@4"></script>
  <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@300;400;600;700;800&display=swap" rel="stylesheet">
  <style>
    body {
      font-family: 'Outfit', sans-serif;
      background-color: #0b0f19;
      color: #f1f5f9;
    }
    table {
      border-collapse: collapse;
      width: 100%;
    }
    th, td {
      border: 1px solid #1e293b;
    }
    @media print {
      .no-print {
        display: none !important;
      }
      @page {
        size: A4 landscape;
        margin: 0.5cm;
      }
      body {
        background-color: #ffffff !important;
        color: #000000 !important;
        padding: 0 !important;
      }
      table {
        border: 2px solid #000000 !important;
      }
      th, td {
        border: 1px solid #000000 !important;
        color: #000000 !important;
        background-color: #ffffff !important;
      }
      .bg-day {
        background-color: #f1f5f9 !important;
        color: #000000 !important;
      }
      .bg-lunch {
        background-color: #e2e8f0 !important;
        color: #000000 !important;
      }
      .legend-card {
        border: 1px solid #000000 !important;
        background-color: #ffffff !important;
        color: #000000 !important;
      }
    }
  </style>
</head>
<body class="p-6 min-h-screen">

  <div class="max-w-6xl mx-auto space-y-5">
    
    <!-- Top Action Bar (Screen Only) -->
    <div class="no-print flex justify-between items-center bg-slate-900/80 border border-slate-800 rounded-xl p-4 shadow-lg">
      <div class="flex items-center space-x-3">
        <span class="px-2.5 py-1 bg-purple-500/10 text-purple-400 border border-purple-500/20 rounded font-bold text-xs">
          DOCUMENT #01 • CLASS TIMETABLE
        </span>
        <span class="text-slate-300 text-sm font-semibold">
          {{ $classroomId }} • Semester {{ $semester }}
        </span>
      </div>
      <div class="flex items-center space-x-3">
        <button onclick="window.print()" class="px-4 py-2 bg-gradient-to-r from-sky-500 via-cyan-500 to-blue-600 hover:from-sky-400 hover:to-blue-500 text-white font-bold rounded-lg text-xs transition-all shadow-md cursor-pointer flex items-center space-x-1.5 border border-sky-400/30">
          <svg class="w-4 h-4" fill="none" stroke="currentColor" viewBox="0 0 24 24"><path stroke-linecap="round" stroke-linejoin="round" stroke-width="2" d="M17 17h2a2 2 0 002-2v-4a2 2 0 00-2-2H5a2 2 0 00-2 2v4a2 2 0 002 2h2m2 4h6a2 2 0 002-2v-4a2 2 0 00-2-2H9a2 2 0 00-2 2v4a2 2 0 002 2zm8-12V5a2 2 0 00-2-2H7a2 2 0 00-2 2v4h14z"/></svg>
          <span>Print Timetable</span>
        </button>
        <button onclick="window.close()" class="px-4 py-2 bg-sky-500/15 hover:bg-sky-500 text-sky-300 hover:text-white border border-sky-500/30 font-bold rounded-lg text-xs transition-all cursor-pointer">
          Close Window
        </button>
      </div>
    </div>

    @if(empty($timetableData))
      <div class="no-print p-3 bg-amber-500/10 border border-amber-500/30 rounded-xl text-amber-300 text-xs font-semibold text-center">
        ⚠️ <strong>Notice:</strong> Weekly timetable schedule has not been generated by HOD yet for <strong>{{ $classroomId }}</strong>. Displaying standard blank timetable template for manual layout and printing.
      </div>
    @endif

    <!-- Header Section -->
    <div class="text-center border-b border-slate-800 pb-4 space-y-1">
      <h1 class="text-base font-extrabold uppercase tracking-widest text-indigo-400">Carmel Polytechnic College, Alappuzha</h1>
      <h2 class="text-xl font-bold text-white uppercase">Department of {{ $fullDept }}</h2>
      <p class="text-xs text-slate-400 font-bold tracking-wider">
        CLASS PROGRAM TIMETABLE — SEMESTER {{ $semester }} (BATCH: {{ $classroomId }})
      </p>
    </div>

    <!-- Timetable Grid -->
    <div class="overflow-x-auto rounded-xl border border-slate-800 shadow-xl bg-slate-950">
      <table class="w-full text-center border-collapse">
        <thead>
          <tr class="bg-slate-900 text-slate-300 font-bold text-xs uppercase tracking-wider">
            <th class="p-3 w-20 bg-day">Day Order</th>
            <th class="p-3">Period 1<br><span class="text-[10px] text-slate-400 font-normal">09:00 - 10:00</span></th>
            <th class="p-3">Period 2<br><span class="text-[10px] text-slate-400 font-normal">10:00 - 11:00</span></th>
            <th class="p-3">Period 3<br><span class="text-[10px] text-slate-400 font-normal">11:10 - 12:10</span></th>
            <th class="p-3 w-12 bg-lunch text-[10px]">Lunch</th>
            <th class="p-3">Period 4<br><span class="text-[10px] text-slate-400 font-normal">01:00 - 02:00</span></th>
            <th class="p-3">Period 5<br><span class="text-[10px] text-slate-400 font-normal">02:00 - 03:00</span></th>
            <th class="p-3">Period 6<br><span class="text-[10px] text-slate-400 font-normal">03:00 - 04:00</span></th>
          </tr>
        </thead>
        <tbody class="divide-y divide-slate-800 text-xs">
          @php
            $days = ['Day 1', 'Day 2', 'Day 3', 'Day 4', 'Day 5'];
            $scheduledSubjects = [];
          @endphp

          @foreach($days as $idx => $day)
            @php
              $dayData = $timetableData[$day] ?? [];
              $p1 = $dayData[1] ?? ['subject' => '', 'staff' => ''];
              $p2 = $dayData[2] ?? ['subject' => '', 'staff' => ''];
              $p3 = $dayData[3] ?? ['subject' => '', 'staff' => ''];
              $p4 = $dayData[4] ?? ['subject' => '', 'staff' => ''];
              $p5 = $dayData[5] ?? ['subject' => '', 'staff' => ''];
              $p6 = $dayData[6] ?? ['subject' => '', 'staff' => ''];

              foreach([$p1, $p2, $p3, $p4, $p5, $p6] as $slot) {
                if(!empty($slot['subject'])) {
                  $scheduledSubjects[$slot['subject']] = true;
                }
              }
            @endphp
            <tr class="hover:bg-slate-900/50 transition-all">
              <td class="p-3 font-bold bg-day text-slate-200 uppercase tracking-wider text-xs">{{ $day }}</td>

              <!-- Forenoon Periods 1-3 -->
              <td class="p-2.5">
                <div class="font-extrabold text-indigo-300 text-xs">{{ $p1['subject'] ?: '--' }}</div>
                <div class="text-[10px] text-slate-400 mt-0.5">{{ $p1['staff'] ?: '' }}</div>
              </td>
              <td class="p-2.5">
                <div class="font-extrabold text-indigo-300 text-xs">{{ $p2['subject'] ?: '--' }}</div>
                <div class="text-[10px] text-slate-400 mt-0.5">{{ $p2['staff'] ?: '' }}</div>
              </td>
              <td class="p-2.5">
                <div class="font-extrabold text-indigo-300 text-xs">{{ $p3['subject'] ?: '--' }}</div>
                <div class="text-[10px] text-slate-400 mt-0.5">{{ $p3['staff'] ?: '' }}</div>
              </td>

              <!-- Lunch Break -->
              @if($idx === 0)
                <td rowspan="5" class="bg-lunch text-slate-400 font-extrabold text-xs uppercase tracking-widest" style="writing-mode: vertical-rl; transform: rotate(180deg); vertical-align: middle;">
                  LUNCH BREAK
                </td>
              @endif

              <!-- Afternoon Periods 4-6 -->
              <td class="p-2.5">
                <div class="font-extrabold text-indigo-300 text-xs">{{ $p4['subject'] ?: '--' }}</div>
                <div class="text-[10px] text-slate-400 mt-0.5">{{ $p4['staff'] ?: '' }}</div>
              </td>
              <td class="p-2.5">
                <div class="font-extrabold text-indigo-300 text-xs">{{ $p5['subject'] ?: '--' }}</div>
                <div class="text-[10px] text-slate-400 mt-0.5">{{ $p5['staff'] ?: '' }}</div>
              </td>
              <td class="p-2.5">
                <div class="font-extrabold text-indigo-300 text-xs">{{ $p6['subject'] ?: '--' }}</div>
                <div class="text-[10px] text-slate-400 mt-0.5">{{ $p6['staff'] ?: '' }}</div>
              </td>
            </tr>
          @endforeach
        </tbody>
      </table>
    </div>

    <!-- Subject Legend & Course Allocations -->
    <div class="bg-slate-900/60 border border-slate-800 rounded-xl p-4 space-y-3 legend-card">
      <h3 class="text-xs font-bold uppercase tracking-wider text-slate-300 border-b border-slate-800 pb-2">
        Course Legend & Assigned Faculty List — Semester {{ $semester }}
      </h3>
      <div class="grid grid-cols-1 md:grid-cols-2 gap-2 text-xs">
        @forelse($allocatedSubjects as $sub)
          @php
            $staffNames = [];
            if ($sub->staffAssignments && $sub->staffAssignments->count() > 0) {
              foreach($sub->staffAssignments as $sa) {
                $st = $sa->staff ?: $sa->staffProfile;
                if ($st && !empty($st->name)) {
                  $staffNames[] = $st->name;
                }
              }
            }
            $staffDisplay = count($staffNames) > 0 ? implode(', ', $staffNames) : 'Unassigned';
          @endphp
          <div class="flex items-center space-x-2 p-2 bg-slate-950/60 rounded-lg border border-slate-800/80">
            <span class="font-mono font-bold text-indigo-400 w-24 text-[11px]">{{ $sub->subject_code }}</span>
            <div class="flex-grow">
              <div class="font-semibold text-slate-200 text-xs">{{ $sub->subject_name }}</div>
              <div class="text-[10px] text-slate-400">Faculty: {{ $staffDisplay }}</div>
            </div>
          </div>
        @empty
          <div class="col-span-full text-slate-500 text-xs italic">No courses registered for this batch/semester yet.</div>
        @endforelse
      </div>
    </div>

    <!-- Signature Footer -->
    <div class="pt-8 grid grid-cols-3 text-center text-xs font-bold text-slate-400">
      <div>
        <div class="h-10"></div>
        <p class="border-t border-slate-800 pt-1 mx-6">Staff Advisor</p>
      </div>
      <div>
        <div class="h-10"></div>
        <p class="border-t border-slate-800 pt-1 mx-6">Head of Department</p>
      </div>
      <div>
        <div class="h-10"></div>
        <p class="border-t border-slate-800 pt-1 mx-6">Principal / Academic Coordinator</p>
      </div>
    </div>

  </div>

</body>
</html>
